### PR TITLE
CLN: Remove the unnecessary line continuation ...

### PR DESCRIPTION
**Pull request by prabhuramachandran**
... this causes problems when apptools is installed on some Windows
machines leading to pain when installing Mayavi.

### CODE REVIEW

**Comment by mdickinson** [comment]
Changes LGTM, too, but as @rahulporuri says it would be good to understand why this is an issue. The original code _should_ be perfectly valid, so if it's being rejected then it's likely something else is wrong.

**Comment by prabhuramachandran** [comment]
Sorry I don't have more information but here is a recent ticket on Mayavi: https://github.com/enthought/mayavi/issues/817 that demonstrates the issue.  I've seen folks running into it but am not sure how this ends up happening when apptools is installed on Windows with Python 3.7 on anaconda.

**Comment by mdickinson** [comment]
@prabhuramachandran I'm going to close this PR. Given that we're not longer using 2to3 on master, this change isn't really useful. At this point, what we really need is a release of apptools.

**Comment by mdickinson** [comment]
> At this point, what we really need is a release of apptools.

Followup: apptools 4.5.0 was released Oct 10th 2019.

**Pull request closed without merging**
