### PR TITLE
Stop using Appveyor CI

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR removes the appveyor configuration file and a related utility used to install edm on appveyor jobs. Two other similar scripts which are unused are also removed in this PR,

This PR is one step towards enthought/ets#63

**Checklist**
- [ ] ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~

### CODE REVIEW

**Comment by rahulporuri** [comment]
Note that I updated the branch protection settings in this repository to remove "Appveyor CI" as a required check and instead include the GitHub Actions CI checks as required.

**Review by aaronayres35 — APPROVED** [review]
LGTM

Although it looks like CI is still unhappy with `AppVeyor build failed` even though it is no longer a required check

**Comment by rahulporuri** [comment]
> Although it looks like CI is still unhappy with AppVeyor build failed even though it is no longer a required check

Same mistake here as before - I didn't disable builds on branches without a configuration file - until after I created this PR.

**Comment by rahulporuri** [comment]
I removed the appveyor CI webhooks from this repository

**Pull request merged**
