### PR TITLE
[WIP] Remove use of 2to3

### PR DESCRIPTION
**Pull request by rahulporuri**
`apptools` currently uses `2to3` to support python >3. 

- Note that this PR drops testing for 3.4

### CODE REVIEW

**Comment by rkern** [comment]
LGTM.

**Comment by rahulporuri** [comment]
_this is puzzling. i opened this PR to show that the tests were failing on 3.5/3.6_

**Comment by rahulporuri** [comment]
Note also that I switched off the push builds on travis

**Comment by rahulporuri** [comment]
closing this PR as it isn't a worthwhile effort at the moment to remove usage of 2to3 completely. opening a separate PR to test travis on 3.5/3.6

**Pull request closed without merging**
