### PR TITLE
Python 3 compatibility and Travis integration

### PR DESCRIPTION
**Pull request by pradyunsg**
This PR adds Python 3 compatibility and Travis integration to apptools.

See commits messages for summary.

### CODE REVIEW

**Comment by jonathanrocher** [comment]
@pradyun What is the status of this branch? It would be great to get it in since it was LGTM-ed by @rkern ... (Python 3 is great but travisCI is what I am after right now...).

**Comment by pradyun** [comment]
@jonathanrocher Well, this PR brought 2 things:

1. Python3 compatibility.  
  The branch is now a little old and thus outdated. So, the Python 3 porting related stuff would need a re-visit, for which I don't have the time as of today.
2. Travis CI Integration  
  The CI build uses Python 3 ports of the other Enthought packages (that I did) and a pre-built PySide egg for Linux, hosted in a Github repository (It was a bad idea, but it was meant to be temporary anyway.).  
  Using enthought's repositories instead of my Python 3 ports of the same and hosting the PySide wheels in a better, more permanent place (or maybe making use of Travis's [Caching][caching] to cache the wheels.) should be enough.

 [caching]: http://docs.travis-ci.com/user/caching

**Comment by jonathanrocher** [comment]
Thanks @pradyun . Would you be opposed to closing this one in favor of 2 different PRs for the 2 parts? I could (try to find the time to) reuse your work on TravisCI and try to get that in and let the Python3 be added independently by you or someone else who has experience with that process.

**Comment by pradyun** [comment]
@jonathanrocher Well, I'm not opposed to breaking this down into 2 PRs for them. (It made sense to make one back then, not so much now...)

**Comment by kitchoi** [comment]
Hi @pradyunsg and @jonathanrocher, Most of this PR that implements part 1 (Python3 compatibility) have been merged in #54.  I have tried merging this PR branch with the current master to find the conflicts.  The only major conflict is in .travis.yml
Is there anything in the .travis.yml you would like to be included in the upcoming release?  If so, would you like to close this one and make a separate PR for that?
Thanks!

**Comment by pradyunsg** [comment]
I believe this is completely superseded by #54 and should be closed. But I won't be the one doing it. It'll be one of the admins of the repository.

**Comment by jonathanrocher** [comment]
Yep, closing the PR...

**Pull request closed without merging**
