### PR TITLE
Run black on codebase

### PR DESCRIPTION
**Pull request by aaronayres35**
contributes to #145 

**Checklist**
~- [ ] Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~

### CODE REVIEW

**Comment by rahulporuri** [comment]
@aaronayres35 i'm not a 100% sure how you ran `black`. When I checkout this branch and i run `black apptools`, there are still a number of changes that black applies on the codebase.

**Comment by aaronayres35** [comment]
> @aaronayres35 i'm not a 100% sure how you ran `black`. When I checkout this branch and i run `black apptools`, there are still a number of changes that black applies on the codebase.

first commit I simply ran `black apptools`, second commit I ran `black apptools --line-length=79` as I noticed when I first ran it it made some of the line >80 chars long.  (I think the black default is 88 for whatever reason)

**Comment by rahulporuri** [comment]
Also, just to confirm, what black version did you use? If I use `black` version `20.8b1` from pip, i don't see any additional changes made by `black` when I run `black -l 79 apptools` on this branch.

**Comment by aaronayres35** [comment]
> Also, just to confirm, what black version did you use? If I use `black` version `20.8b1` from pip, i don't see any additional changes made by `black` when I run `black -l 79 apptools` on this branch.

I used `black` version  `20.8b1` from pip as well

**Review by rahulporuri — APPROVED** [review]
LGTM. I think I trust black enough that I didn't verify each individual change made when running black on the codebase.

**Comment by rahulporuri** [comment]
@kitchoi are you okay with this?

**Comment by kitchoi** [comment]
> @kitchoi are you okay with this?

Yes! Sorry I did not add to the review after I saw it has been approved. I agree given this is all automated and I trust the tool enough, I did not review every line. At a glance (with some random sampling), the changes look good to me!

**Pull request merged**
